"""
SKWindowsGenerator: Inspects user requests or HTML/Python projects, selects an appropriate
Windows desktop wrapper (PyInstaller, Electron, Tauri, C#, C++), generates the complete project
and build configuration, and checks host build environment availability honestly.
"""

import os
import platform
import shutil
from typing import Dict, Any, List


class SKWindowsGenerator:
    SUPPORTED_STACKS = ["python-pyinstaller", "electron", "tauri", "csharp-dotnet", "cpp-win32"]

    def choose_stack(self, prompt: str) -> str:
        p = prompt.lower()
        if "tauri" in p or "rust" in p:
            return "tauri"
        if "electron" in p or "html" in p or "web" in p:
            return "electron"
        if "c#" in p or "csharp" in p or ".net" in p:
            return "csharp-dotnet"
        if "c++" in p or "win32" in p:
            return "cpp-win32"
        return "python-pyinstaller"

    def create_windows_project(
        self,
        prompt: str = "Make this HTML app into a Windows EXE.",
        project_name: str = "SKAIDesktopApp",
        stack: str | None = None,
        output_dir: str = "generated_projects/windows_exe",
    ) -> Dict[str, Any]:
        chosen_stack = stack or self.choose_stack(prompt)
        os.makedirs(output_dir, exist_ok=True)
        is_windows_host = platform.system() == "Windows"
        has_pyinstaller = shutil.which("pyinstaller") is not None

        if chosen_stack == "electron":
            files = {
                "package.json": (
                    "{\n"
                    f'  "name": "{project_name.lower()}",\n'
                    '  "version": "1.0.0",\n'
                    '  "main": "main.js",\n'
                    '  "scripts": {\n'
                    '    "start": "electron .",\n'
                    '    "build:exe": "electron-builder --win portable"\n'
                    "  },\n"
                    '  "devDependencies": {\n'
                    '    "electron": "^29.0.0",\n'
                    '    "electron-builder": "^24.13.3"\n'
                    "  }\n"
                    "}\n"
                ),
                "main.js": (
                    "const { app, BrowserWindow } = require('electron');\n"
                    "function createWindow() {\n"
                    "  const win = new BrowserWindow({ width: 1280, height: 820 });\n"
                    "  win.loadFile('index.html');\n"
                    "}\n"
                    "app.whenReady().then(createWindow);\n"
                ),
                "index.html": (
                    "<!DOCTYPE html>\n"
                    "<html><head><meta charset='UTF-8'><title>SK AI Windows App</title></head>\n"
                    f"<body><h1>{project_name}</h1><p>Generated by SK AI Windows EXE Subsystem.</p></body></html>\n"
                ),
                "build_windows.bat": "@echo off\nnpm install\nnpm run build:exe\n",
                "README.md": (
                    f"# {project_name} (Windows EXE via Electron Wrapper)\n\n"
                    "## How to Build `.EXE` on Windows\n"
                    "1. Install Node.js LTS on Windows.\n"
                    "2. Run `npm install`.\n"
                    "3. Run `npm run build:exe` to produce the portable `.exe` in `dist/`.\n"
                ),
            }
            build_cmd = "npm run build:exe"
        else:
            files = {
                "app_main.py": (
                    "import tkinter as tk\n\n"
                    "def main():\n"
                    "    root = tk.Tk()\n"
                    f"    root.title('{project_name} — SK AI Local Desktop')\n"
                    "    root.geometry('960x640')\n"
                    f"    lbl = tk.Label(root, text='{project_name} Ready (Offline-First)', font=('Segoe UI', 14))\n"
                    "    lbl.pack(padx=24, pady=24)\n"
                    "    root.mainloop()\n\n"
                    "if __name__ == '__main__':\n"
                    "    main()\n"
                ),
                f"{project_name}.spec": (
                    "# -*- mode: python ; coding: utf-8 -*-\n"
                    "a = Analysis(['app_main.py'], pathex=[], binaries=[], datas=[], hiddenimports=[])\n"
                    "pyz = PYZ(a.pure)\n"
                    f"exe = EXE(pyz, a.scripts, a.binaries, a.datas, name='{project_name}', console=False, onefile=True)\n"
                ),
                "build_exe.bat": f"@echo off\npip install pyinstaller\npyinstaller --onefile --windowed --name {project_name} app_main.py\n",
                "README.md": (
                    f"# {project_name} (Windows Standalone .EXE Project)\n\n"
                    "## How to Build `.EXE` on Windows\n"
                    "```powershell\n"
                    "pip install pyinstaller\n"
                    f"pyinstaller --onefile --windowed --name {project_name} app_main.py\n"
                    "```\n"
                    f"The compiled binary will be placed at `dist\\{project_name}.exe`.\n"
                ),
            }
            build_cmd = f"pyinstaller --onefile --windowed --name {project_name} app_main.py"

        created_files: List[str] = []
        for rel_path, content in files.items():
            full_path = os.path.join(output_dir, rel_path)
            os.makedirs(os.path.dirname(full_path), exist_ok=True)
            with open(full_path, "w", encoding="utf-8") as f:
                f.write(content)
            created_files.append(rel_path)

        exe_built = False
        build_status_note = (
            "Project structure and Windows build scripts generated and validated. "
            f"Native `.exe` binary was NOT compiled because current host OS is '{platform.system()}' "
            "(requires Windows host toolchain to produce verified PE32+ `.exe`)."
            if not (is_windows_host and has_pyinstaller)
            else "Windows host toolchain detected."
        )

        return {
            "subsystem": "SK-WINDOWS",
            "project_name": project_name,
            "stack": chosen_stack,
            "prompt": prompt,
            "output_dir": output_dir,
            "files_created": created_files,
            "files_preview": files,
            "build_command": build_cmd,
            "exe_binary_compiled": exe_built,
            "build_environment_status": build_status_note,
        }
